### ISSUE TITLE
Support GitHub login changes by students

### ISSUE THREAD

**Issue by 0xf8f8ff** [quickfeed/quickfeed#340]
When a student changes a GitHub login the application will try to fetch him by the old login, resulting in all kinds of errors, and currently can only be resolved by manual updates to the database and repositories. 
To simplify the process, we should allow updating a student's GitHub login from the application's GUI and then update the name student's repository accordingly.
A question to consider: should we allow the students to update their logins or should it be a feature only available to the course teachers (eventually admins)?

**Comment by meling** [comment]
Is there a way to ask GitHub for the new name, or otherwise detect the new name? It would be nice to implement this without user interaction. Either way, if we have to implement this as a UI element, we should discourage users from changing their GitHub user name when they sign up... (give their name and student ID)... 

To your question, if we can implement this robustly, I don't thing we need admins/teachers to be involved. My concern is that if students do this, they will run into problems, or our solution won't always work... For instance, how can this be done after a user has changed the user name on GitHub and then tries to log into Quickfeed with the new user name, and we don't recognize the user... how should the user be able to claim his old account? He would probably be sent to the signup page to give name and student ID and email, and they would conflict with the old user's name and student ID etc... (though I'm not sure we actually check for duplicate entries...)

We need a more detailed description of how this should work before investing time to implement this.

**Comment by 0xf8f8ff** [comment]
Not implemented yet. One problem I see is how we work with student repositories. Let's say a student changes GitHub login from `A` to `B`. Their GItHub's remote ID does not change and there should be no problems with logging in. Additionally, we fetch all the user info from GitHub on login and it looks simple to just update the `User.login` in the database in case there is a mismatch between the database record and GItHub info.

But it is possible that at this moment the user is already enrolled in a course and has an `A-labs` repository. If we update the user's login in the database, QF will start looking for `B-labs` repo for this user which would result in multiple errors.

One solution is to rename the student's repository in case there was a change to the user's GitHub login.

**Comment by JosteinLindhom** [comment]
The added complexity is not worth it.
