### ISSUE TITLE
GORM Update from struct with zero value fields may not work correctly

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#570]
As was discovered today, and also previously, GORM does not update fields with zero value, e.g., bool = false. There are two workarounds for this problem, as mentioned in [this comment](https://github.com/quickfeed/quickfeed/issues/569#issuecomment-1013729572).

We should examine all uses of GORM `Update(s)` and check that updates are correctly stored in the database.

Also we should use the [`Select`](https://gorm.io/docs/update.html#Update-Selected-Fields) approach to ensure that zero value fields of the struct are updated. Using `Select` is preferred because it will allow us to rename the struct fields cleanly, which would not be the case with the `map[string]interface{}` approach, where each field name of the struct would be a string that a type-safe rename would not find.

**Comment by 0xf8f8ff** [comment]
So after two days of struggling with gorm there are two major conclusions:

1. Using `Select("*").Updates(...)` is dangerous. For example, 

```
Model(&qf.Enrollment{}).Where(~conditions~).Select("*").Updates(Updates(&qf.Enrollment{State: enrol.State, Status: enrol.Status, LastActivityDate: enrol.LastActivityDate}))
```

will set all the fields not mentioned in `Updates` (for example, `UserID` and `CourseID`) to default values. Currently there is no way to ensure we are always sending query structs where all the fields are set to the relevant values (most often then not fields not relevant to the method are left empty).

The alternative would be using `Select` with field names like `Select("State", "Status", "LastActivityDate")`, but it defeats the purpose as there is still dependency on strings representing field names which we would like to avoid.

Another possibility is fetching the original record inside the database method before updating. Then we could update only the changed fields and use this struct as a query in `Updates` if we don't mind an extra database lookup.

2. Database method `UpdateEnrollments` is used from many places and works correctly only because of this gorm's "feature" of not updating fields to their defaul values with a simple `Updates`.

For example, when updating activity date with `UpdateEnrollment(query)`, the query has empty fields for enrollment `Status` and `State`. Without this gorm's "feature" both these fields would be reset to default values. I don't know how safe it is because if gorm suddenly changes this behaviour the impact on the database will be huge.

However, rewriting `UpdateEnrollment` with `Select` requires changes to all the methods that call it (in most cases an additional call to the database to fetch the original enrollments to ensure ther eare no fiels unintentionally set to defaul values).

**Comment by meling** [comment]
Okay, I see. Without digging too deeply into the code that may need to be updated... We should implement our API to be intuitive and easy to use, even though we may take a performance hit by having to do a fetch query before an update. We can probably do the fetch and update as a single transaction. I prefer an API that makes sense over a difficult-to-use one, even if the implementation is a bit awkward.

For the long term, I plan to propose a bachelor project to review alternative database ORMs with generics support or other non-ORM alternatives. Therefore, our database API should not depend heavily on GORM's idiosyncrasies.
